# Cleaning data using Pandas

In [1]:
import pandas as pd

C:\Users\user\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\user\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_excel("Downloads/Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

### 1) understand the data set

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         21 non-null     int64
 1   First_Name         21 non-null     str
 2   Last_Name          20 non-null     str
 3   Phone_Number       19 non-null     object
 4   Address            21 non-null     str
 5   Paying Customer    21 non-null     str
 6   Do_Not_Contact     17 non-null     str
 7   Not_Useful_Column  21 non-null     bool
dtypes: bool(1), int64(1), object(1), str(5)
memory usage: 2.0+ KB

### 2) check for duplicates, if there so drop them

In [5]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [8]:
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

### 3) drop columns that not useful

In [15]:
# df = df.drop(columns= "Not_Useful_Column")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

### 4) work with every column, see which one need cleaning
#### for example the last name has many errors need to be clearn

In [20]:
df["Last_Name"]

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: str

In [24]:
# this line make us replace any characters we need by empty space
df["Last_Name"] = df["Last_Name"].str.replace(r"[._/]", "", regex=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

#### then work with the phone numbers column

In [26]:
df["Phone_Number"]

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              NaN
7     876|678|3469
8              N/a
9     123-545-5421
10             NaN
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

In [49]:
df["Phone_Number"] = df["Phone_Number"].str.replace(r"\D", "", regex=True)

In [52]:
df["Phone_Number"] = df["Phone_Number"].fillna(0)

In [54]:
df["Phone_Number"] = df["Phone_Number"].replace("" , 0)

In [55]:
df["Phone_Number"]

0     1235455421
1     1236439775
2              0
3     1235432345
4     8766783469
5     3047622467
6              0
7     8766783469
8              0
9     1235455421
10             0
11             0
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17             0
18             0
19    8766783469
Name: Phone_Number, dtype: object

In [56]:
formatted_numbers = []

for phone in df["Phone_Number"]:
    phone = str(phone)      # Make sure it's a string

    formatted = ""

    for i, digit in enumerate(phone):
        formatted += digit

        if i == 2 or i == 5:
            formatted += "-"

    formatted_numbers.append(formatted)

df["Phone_Number"] = formatted_numbers

In [59]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,0,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,0,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,0,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,0,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,0,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,0,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,0,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

#### handle the address column by seperating

In [60]:
df["Address"] = df["Address"].replace("N/a", pd.NA)
df["Address"] = df["Address"].fillna("Unknown")
df["Address"] = df["Address"].str.title()


df["House_Number"] = df["Address"].str.extract(r"^(\d+)")
df["ZIP_Code"] = df["Address"].str.extract(r"(\d{5})$")
df["City"] = df["Address"].str.extract(r",\s*([^,]+?)(?:,\s*\d{5})?$")
df["Street"] = (
    df["Address"]
    .str.replace(r"^\d+\s*", "", regex=True)
    .str.replace(r",.*", "", regex=True)
)
df["Street"] = df["Street"].str.replace(r"\s+", " ", regex=True).str.strip()

In [61]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,House_Number,ZIP_Code,City,Street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123,NaN,Shire,Shire Lane
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93,NaN,NaN,West Main Street
2,1003,Walter,White,0,298 Drugs Driveway,N,NaN,298,NaN,NaN,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980,18503,Pennsylvania,Paper Avenue
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123,NaN,NaN,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768,NaN,NaN,City Parkway
6,1007,Jeff,Winger,0,1209 South Street,No,No,1209,NaN,NaN,South Street
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98,NaN,NaN,Clue Drive
8,1009,Gandalf,NaN,0,123 Middle Earth,Yes,NaN,123,NaN,NaN,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25Th Main Street, New York",Yes,No,25,NaN,New York,Th Main Street
10,1011,Samwise,Gamgee,0,"612 Shire Lane, Shire",Yes,No,612,NaN,Shire,Shire Lane
11,1012,Harry,Potter,0,2394 Hogwarts Avenue,Y,NaN,2394,NaN,NaN,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039,NaN,NaN,Main Street
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343,NaN,NaN,City Parkway
14,1015,Toby,Flenderson,304-762-2467,214 Hr Avenue,N,No,214,NaN,NaN,Hr Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395,NaN,NaN,Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121,NaN,Pennsylvania,Paper Avenue
17,1018,Clark,Kent,0,3498 Super Lane,Y,NaN,3498,NaN,NaN,Super Lane
18,1019,Creed,Braton,0,Unknown,N/a,Yes,NaN,NaN,NaN,Unknown
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910,NaN,Tatooine,Tatooine Road

#### Paying Customer column

In [62]:
df["Paying Customer"]

0     Yes
1      No
2       N
3     Yes
4       Y
5     Yes
6      No
7       N
8     Yes
9     Yes
10    Yes
11      Y
12    Yes
13    Yes
14      N
15     No
16    Yes
17      Y
18    N/a
19    Yes
Name: Paying Customer, dtype: str

In [73]:
df["Paying Customer"] = df["Paying Customer"].replace(["Unknown", "Y"], "Yes")
df["Paying Customer"] = df["Paying Customer"].replace("N", "No")
df["Paying Customer"]

0     Yes
1      No
2      No
3     Yes
4     Yes
5     Yes
6      No
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13    Yes
14     No
15     No
16    Yes
17    Yes
18    Yes
19    Yes
Name: Paying Customer, dtype: str

#### Do_Not_Contact Column

In [74]:
df["Do_Not_Contact"]

0      No
1     Yes
2     NaN
3       Y
4      No
5     Yes
6      No
7      No
8     NaN
9      No
10     No
11    NaN
12      N
13     No
14     No
15      N
16     No
17    NaN
18    Yes
19      N
Name: Do_Not_Contact, dtype: str

In [83]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].replace("Y" , "Yes")
df["Do_Not_Contact"]

0      No
1     Yes
2     NaN
3     Yes
4      No
5     Yes
6      No
7      No
8     NaN
9      No
10     No
11    NaN
12      N
13     No
14     No
15      N
16     No
17    NaN
18    Yes
19      N
Name: Do_Not_Contact, dtype: str

In [84]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].replace("N" , "No")
df["Do_Not_Contact"]

0      No
1     Yes
2     NaN
3     Yes
4      No
5     Yes
6      No
7      No
8     NaN
9      No
10     No
11    NaN
12     No
13     No
14     No
15     No
16     No
17    NaN
18    Yes
19     No
Name: Do_Not_Contact, dtype: str

In [87]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].fillna("Yes")
df["Do_Not_Contact"]

0      No
1     Yes
2     Yes
3     Yes
4      No
5     Yes
6      No
7      No
8     Yes
9      No
10     No
11    Yes
12     No
13     No
14     No
15     No
16     No
17    Yes
18    Yes
19     No
Name: Do_Not_Contact, dtype: str

In [88]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,House_Number,ZIP_Code,City,Street
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123,NaN,Shire,Shire Lane
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93,NaN,NaN,West Main Street
2,1003,Walter,White,0,298 Drugs Driveway,No,Yes,298,NaN,NaN,Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,980,18503,Pennsylvania,Paper Avenue
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Yes,No,123,NaN,NaN,Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768,NaN,NaN,City Parkway
6,1007,Jeff,Winger,0,1209 South Street,No,No,1209,NaN,NaN,South Street
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,No,No,98,NaN,NaN,Clue Drive
8,1009,Gandalf,NaN,0,123 Middle Earth,Yes,Yes,123,NaN,NaN,Middle Earth
9,1010,Peter,Parker,123-545-5421,"25Th Main Street, New York",Yes,No,25,NaN,New York,Th Main Street
10,1011,Samwise,Gamgee,0,"612 Shire Lane, Shire",Yes,No,612,NaN,Shire,Shire Lane
11,1012,Harry,Potter,0,2394 Hogwarts Avenue,Yes,Yes,2394,NaN,NaN,Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,No,2039,NaN,NaN,Main Street
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343,NaN,NaN,City Parkway
14,1015,Toby,Flenderson,304-762-2467,214 Hr Avenue,No,No,214,NaN,NaN,Hr Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,No,2395,NaN,NaN,Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121,NaN,Pennsylvania,Paper Avenue
17,1018,Clark,Kent,0,3498 Super Lane,Yes,Yes,3498,NaN,NaN,Super Lane
18,1019,Creed,Braton,0,Unknown,Yes,Yes,NaN,NaN,NaN,Unknown
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No,910,NaN,Tatooine,Tatooine Road